- name: MAKE PPPoe Server
  hosts: all
  gather_facts: no
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  roles:
  - pppoe
