ansible_connection: network_cli
ansible_network_os: community.routeros.routeros
ansible_user: admin
ansible_password: admin
ansible_become: false

# WireGuard
wg_name: wg0
wg_listen_port: 13231
wg_network: 10.10.10.0/24

wg_fw_comment: "Allow WireGuard"
wg_nat_comment: "WG no NAT"
