---
- name: ospf && bgp
  gather_facts: no
  hosts: all
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  roles:
   - BGP-OSPF
