ansible_host: 192.168.1.111
ips:
 - ip: "10.20.30.2/31"
   ether: "ether1"
 - ip: "10.10.10.3/31"
   ether: "ether2"
 - ip: "10.11.12.2/31"
   ether: "ether3"
#dhcp_network: "192.168.188.0/24"
#dhcp_gateway: "192.168.188.1"
identity: "egypt"
loopback:
 name: "lo_1"
 ip: "11.11.11.11/32"
ospf:
   instance: "ospf-instance-1"
   disabled: no
   area: "ospf-area-one"
   area_id: "0.0.0.0"
interfaces:
  - interface: ether3
    network_type: ptp
    passive: false
  - interface: ether2
    network_type: ptp
    passive: false
  - interface: ether1
    network_type: ptp
    passive: false
#pool:
 #name: "pool_one"
 #range: "192.168.188.50-192.168.188.200"
#dhcp:
 #name: "dh_one"
 #interface: "ether4"
bgp:
 - connection: To-USA
   remote_as: 300
   remote_address: 10.11.12.3
   role: ibgp
   local: 10.11.12.2
   #redistr: connected
   output_network: public_1
 - connection: To-SYRIA
   remote_as: 300
   remote_address: 10.10.10.2
   role: ibgp
   local: 10.10.10.3
   #redistr: connected
   output_network: public_1
 - connection: To-LEBANON
   remote_as: 300
   remote_address: 10.20.30.3
   role: ibgp
   local: 10.20.30.2
   #redistr: connected
   output_network: public_1
bgp_base:
   temp: "temp_1"
   as: "300"
address_list:
 - list: "public_1"
   address: ""
 - list: "public_1"
   address: ""
