ansible_host: 192.168.1.150
ips:
 - ip: "70.70.70.0/31"
   ether: "ether1"
 - ip: "80.80.80.1/31"
   ether: "ether2"
 - ip: "90.90.90.0/31"
   ether: "ether3"
identity: "kanada"
loopback:
 name: "lo_1"
 ip: "101.101.101.101/32"
bgp:
 - connection: To-MEXICO
   remote_as: 400
   remote_address: 80.80.80.0
   role: ebgp
   local: 80.80.80.1
   #redistr: connected
   output_network: public_1
 - connection: To-USA
   remote_as: 300
   local: 90.90.90.0
   remote_address: 90.90.90.1
   role: ebgp
   output_network: public_2
   #redistr: connected
 - connection: To-AMAZON
   remote_as: 200
   local: 70.70.70.0
   remote_address: 70.70.70.1
   role: ebgp
   output_network: public_3
   #redistr: connected
bgp_base:
   temp: "temp_1"
   as: "100"
address_list:
  - list: "public_1"
    address: 70.70.70.0/31
  - list: "public_1"
    address: 90.90.90.0/31
  - list: "public_2"
    address: 80.80.80.0/31
  - list: "public_2"
    address: 70.70.70.0/31
  - list: "public_3"
    address: 90.90.90.0/31
  - list: "public_3"
    address: 80.80.80.0/31
