ansible_host: 192.168.1.110
wg_role: spoke
wg_ip: 10.10.10.3/24

wan_ip: 172.16.100.3/24
wan_interface: ether1

lan_subnet: 192.168.20.0/24
lan_interface: ether3
lan_ip: 192.168.20.1/24
allow_addr: 192.168.20.1
