---
- name: tasks for routeros
  hosts: all
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      password: "{{ ansible_password }}"
      username: "{{ ansible_user }}"
  gather_facts: no
  roles:
   - capsman
