---
- name: assign_ip_address
  community.routeros.api_modify:
    path: ip address
    data:
      - address: "{{ item.ip }}"
        interface: "{{ item.ether }}"
  loop: "{{ ips }}"
  when: ips is defined
