ansible_host: 172.16.10.2
loopback:
 name: "lo_id"
 id: "7.7.7.7/32"
interfaces:
  - interface: ether1
    network_type: ptp
    passive: false
  - interface: ether3
    network_type: ptp
    passive: false
bgp:
 - con: To-RR
   remote_as: 6502
   remote_address: 172.16.20.2
   role: ibgp
   redistr: connected
 - con: To-ISP2
   remote_as: 6501
   remote_address: 172.16.10.1
   role: ebgp
   redistr: connected
bgp_base:
   temp: "temp_1"
   as: "6502"
