---
- name: STP FOR SWITCHES
  hosts: all
  gather_facts:
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
  roles:
   - stp
