ansible_host: 192.168.12.2
lo_ip: "3.3.3.3/32"
bgp_in:
  name: inst_3
  id: 3.3.3.3
  as: 3
conn:
 - remote_add: 172.16.0.2
   remote_as: 3
   conn_name: ibgp_r2
   role: ibgp
 - remote_add: 192.168.12.1
   remote_as: 1
   conn_name: ibgp_isp1
   role: ebgp
 - remote_add: 192.168.13.1
   remote_as: 2
   conn_name: ibgp_isp2
   role: ebgp
ips:
  - 192.168.12.0/24
  - 3.3.3.3/32
  - 192.168.13.0/24
  - 172.16.0.0/24
